### GENERATING SOME SYNTHETIC PII DATA

In [2]:
!pip install faker

Collecting faker
  Downloading Faker-28.4.1-py3-none-any.whl (1.8 MB)
     ---------------------------------------- 1.8/1.8 MB 4.7 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.4 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from faker) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from python-dateutil>=2.4->faker) (1.16.0)
Installing collected packages: faker
Successfully installed faker-28.4.1

[notice] A new release of pip is available: 23.1.2 -> 24.2
[notice] To update, run: C:\Users\hp\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [3]:
import random
import faker
import pandas as pd

In [4]:
# Initialize Faker library to generate fake data
fake = faker.Faker()

def generate_pii_data(num_records=1000):
    pii_data = []
    
    for _ in range(num_records):
        record = {
            'Name': fake.name(),
            'Email': fake.email(),
            'Phone Number': fake.phone_number(),
            'SSN': fake.ssn(),
            'Credit Card Number': fake.credit_card_number(),
            'IP Address': fake.ipv4(),
            'Address': fake.address().replace("\n", " "),
            'Date of Birth': fake.date_of_birth().strftime('%Y-%m-%d')
        }
        pii_data.append(record)
    
    return pd.DataFrame(pii_data)

# Generate a dataset with 1,000 records
pii_dataset = generate_pii_data(1000)

In [5]:
pii_dataset

,Name,Email,Phone Number,SSN,Credit Card Number,IP Address,Address,Date of Birth
0,Kimberly Stout,kelly00@example.com,695.593.0676x70050,772-68-9340,3580302966034375,202.168.67.82,"38302 Smith Junction New Kirkhaven, KY 18410",1997-09-26
1,Jeanette Scott,barajasdennis@example.com,(758)555-1670x46243,443-22-9091,213151288809043,158.245.89.106,"3757 Ryan Stream Jeffreyfurt, TN 72053",1930-09-03
2,David Brown,steven90@example.com,001-708-641-8838,316-26-0569,2697170525811712,36.111.65.226,"91182 Kirby Greens Suite 148 North Donna, MO 9...",1943-03-20
3,Daniel Velez,ann17@example.com,(563)404-9358x22390,024-86-8887,502010679939,134.15.6.100,"0310 Melissa Loaf Brandonchester, CA 72179",2011-09-16
4,Angela Williams,chadbrown@example.org,(520)242-4090x64452,479-32-8943,3554515070921607,129.95.29.250,"5020 Dixon Glens Monicafurt, KS 53419",1957-11-03
...,...,...,...,...,...,...,...,...
995,Robert Barton,oguerrero@example.org,(537)417-1878,312-30-9761,6011865998515555,89.30.103.7,"445 Kyle Club West Brianmouth, NJ 96672",2006-01-30
996,Amy Hunt,qbrown@example.org,996.291.3690x65088,133-63-0704,3579865065113087,63.18.182.254,"0770 Stephen Forge East Aaronmouth, HI 46344",2012-10-16
997,Lisa Ward,elizabethwilkerson@example.org,256.353.2976,296-55-9571,3540948129318193,209.237.24.213,Unit 4378 Box 8557 DPO AE 52017,1963-04-08
998,Sabrina Espinoza,bethanyjones@example.net,+1-945-422-7719x34073,245-17-3731,4778143662927631,122.35.215.219,"0713 Jessica Freeway Suite 946 Hudsonville, FM...",1948-10-31
999,Jennifer Cain,adamkennedy@example.com,887.598.5615x18510,400-79-1675,30567669227979,117.167.224.32,"PSC 1456, Box 4854 APO AP 59499",1985-03-22

In [6]:
# Save as CSV file for ingestion
pii_dataset.to_csv('pii_data.csv', index=False)